In [2]:
from numpy import*
a=array([1,2,3,4])
b=array([5,6,7,8])

In [3]:
a

array([1, 2, 3, 4])

In [4]:
b

array([5, 6, 7, 8])

In [5]:
a+b

array([ 6,  8, 10, 12])

In [6]:
a*2

array([2, 4, 6, 8])

In [7]:
a**2

array([ 1,  4,  9, 16], dtype=int32)

In [8]:
a.dot(b)

70